section_name:
  # Link or ID of the Telegram channel.
  # for example:
  # tg_channel = "@durov"
  # tg_channel = -1234567890987
  # Don't forget to add bot to this channel as an administrator!
  tg_channel: "@aaaa"

  # Token for your Telegram bot.
  # You can get it here: https://t.me/BotFather
  tg_bot_token: "1234567890:AAA-AaA1aaa1AAaaAa1a1AAAAA-a1aa1-Aa"

  # Personal token for your VK profile.
  # You can get it here:
  # https://github.com/alcortazzo/vktgbot/wiki/How-to-get-personal-access-token
  vk_token: "00a0a0ab00f0a0ab00f0a6ab0c00000b0f000f000f0a0ab0a00b000000dd00000000de0"
  
  # Part of the link (after vk.com/) to the VK channel
  # for example:
  # if link is vk.com/>>>example<<<
  # vk_domain: "example"
  vk_domain: "bbbb"

  # Version of VK API (https://vk.com/dev/versions).
  # Used for "wall.get" method
  req_version: 5.103
  
  # Number of posts to send to Telegram.
  # Min value = 2
  # Max value = 100
  req_count: 3

  # Filter to apply:
  # "owner" — posts by the wall owner;
  # "others" — posts by someone else;
  # "all" — posts by the wall owner and others
  # "postponed" — timed posts (only available for calls with an access_token)
  # "suggests" — suggested posts on a community wall
  req_filter: owner

  # If True bot will stop after first pass through the loop.
  single_start: false

  # Waiting time (in seconds) between cycle passes.
  time_to_sleep: 120

  # Set True if you want to skip sponsored posts
  skip_ads_posts: true

  # Set True if you want to skip posts with specified Copyright
  skip_copyrighted_posts: false

  # Set True if you don't want to parse reposts
  skip_reposts: false

  # Words whitelist.
  # Bot will repost posts only containing words in whitelist.
  # Useful for hashtags.
  whitelist:
  # Words blacklist.
  # If post contains a blacklisted word, the post will be skipped.
  blacklist:
  # for example:
  # whitelist:
  # - "#music"
  # - "new"
  # blacklist:
  # - "rap"
  # - "dubstep"
  # This configuration will keep posts only with music hashtag
  # and word "new" excluding posts with words "rap" and "dubstep".

  # ID of the last post that was sent to Telegram.
  last_kwown_post_id: 0


# If you want to add more channels, just uncomment and edit this section or add new one.

# any_name_you_want:
#   tg_channel: "@aaaa"
#   tg_bot_token: "1234567890:AAA-AaA1aaa1AAaaAa1a1AAAAA-a1aa1-Aa"
#   vk_token: "00a0a0ab00f0a0ab00f0a6ab0c00000b0f000f000f0a0ab0a00b000000dd00000000de0"
#   vk_domain: "bbbb"

#   req_version: 5.103
#   req_count: 5
#   req_filter: owner

#   single_start: false
#   time_to_sleep: 120
#   skip_ads_posts: true
#   skip_copyrighted_posts: false
#   skip_reposts: false
#   whitelist:
#   - "example text"
#   blacklist:
#   - "another example text"
#   last_kwown_post_id: 0
