FROM python:3.9.7-alpine
WORKDIR /code

COPY requirements.txt ./

RUN apk update &&\
    apk add --no-cache --virtual .build-deps \
        build-base \
        gcc &&\
    pip install --user -r requirements.txt &&\
    apk del .build-deps &&\
    rm -rf /root/* /tmp/*

COPY bot.py config.py last_known_id.txt ./

ARG TG_CHANNEL
ENV VAR_TG_CHANNEL=$TG_CHANNEL

ARG TG_BOT_TOKEN
ENV VAR_TG_BOT_TOKEN=$TG_BOT_TOKEN

ARG VK_TOKEN
ENV VAR_TG_VK_TOKEN=$VK_TOKEN

ARG VK_DOMAIN
ENV VAR_TG_VK_DOMAIN=$VK_DOMAIN

ARG TG_LOG_CHANNEL
ENV VAR_TG_LOG_CHANNEL=$TG_LOG_CHANNEL

ARG TG_BOT_LOG_TOKEN
ENV VAR_TG_BOT_LOG_TOKEN=$TG_BOT_LOG_TOKEN

ARG REQ_VER
ENV VAR_REQ_VER=$REQ_VER

ARG REQ_COUNT
ENV VAR_REQ_COUNT=$REQ_COUNT

ARG REQ_FILTER
ENV VAR_REQ_FILTER=$REQ_FILTER

ARG SINGLE_START
ENV VAR_SINGLE_START=$SINGLE_START

ARG TIMESLEEP
ENV VAR_TIMESLEEP=$TIMESLEEP

ARG IS_PINNED
ENV VAR_IS_PINNED=$IS_PINNED

ARG SKIP_ADS_POSTS
ENV VAR_SKIP_ADS_POSTS=$SKIP_ADS_POSTS

ARG SKIP_POSTS_WITH_COPYRIGHT
ENV VAR_SKIP_POSTS_WITH_COPYRIGHT=$SKIP_POSTS_WITH_COPYRIGHT

ARG WHITELIST
ENV VAR_TG_WHITELIST=$WHITELIST

ARG BLACKLIST
ENV VAR_TG_BLACKLIST=$BLACKLIST

ARG PROXY_ENABLE
ENV VAR_PROXY_ENABLE=$PROXY_ENABLE

ARG PROXY_LOGIN
ENV VAR_PROXY_ENABLE=$PROXY_LOGIN

ARG PROXY_PROXY_PASS
ENV VAR_PROXY_PROXY_PASS=$PROXY_PROXY_PASS

ARG PROXY_PROXY_IP
ENV VAR_PROXY_PROXY_IP=$PROXY_PROXY_IP

ARG PROXY_PROXY_PORT
ENV VAR_PROXY_PROXY_PORT=$PROXY_PROXY_PORT

ARG LOG_FOLDER_NAME
ENV VAR_LOG_FOLDER_NAME=$LOG_FOLDER_NAME

ARG LOG_FILENAME
ENV VAR_LOG_FILENAME=$LOG_FILENAME

CMD ["./bot.py"]
ENTRYPOINT ["python"]

